{ pkgs, lib, config, ... }:
{
  home.username = "hkailahi";
  home.homeDirectory = "/Users/hkailahi";
  home.stateVersion = "22.11";
  programs.home-manager.enable = true;

  home.sessionVariables = {
    EDITOR = "code";
    # Just keep copy of ./etc-nix files in .config/nix since nix.settings and nix.extraOptions refuse to work
    NIX_CONF_DIR = "$HOME/.config/nix";
  };

  nix.package = pkgs.nixVersions.nix_2_15;  # Per https://discourse.nixos.org/t/how-to-upgrade-nix-on-macos-with-home-manager/25147/4

  nix.settings = {
    # Generated by https://github.com/DeterminateSystems/nix-installer, version 0.6.0.
    "bash-prompt-prefix" = "(nix:$name)\040";
    "build-users-group" = "nixbld";
    "extra-nix-path" = "nixpkgs=flake:nixpkgs";
    "experimental-features" = "nix-command flakes";
    "auto-optimise-store" = "true";

    # Manual Additions
    "extra-trusted-substituters" = [
       "https://cache.nixos.org/"
       "https://nix-community.cachix.org"
       "https://cache.floxdev.com"
    ];
    "extra-trusted-public-keys" = [
      "nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs="
      "_FLOX_PUBLIC_KEYS()"
    ];
  };

  nix.registry = {
    agda = { from = { id = "agda"; type = "indirect"; }; to = { owner = "agda"; repo = "agda"; type = "github"; }; };
    arion = { from = { id = "arion"; type = "indirect"; }; to = { owner = "hercules-ci"; repo = "arion"; type = "github"; }; };
    blender-bin = { from = { id = "blender-bin"; type = "indirect"; }; to = { dir = "blender"; owner = "edolstra"; repo = "nix-warez"; type = "github"; }; };
    composable = { from = { id = "composable"; type = "indirect"; }; to = { owner = "ComposableFi"; repo = "composable"; type = "github"; }; };
    dreampkgs = { from = { id = "dreampkgs"; type = "indirect"; }; to = { owner = "nix-community"; repo = "dreampkgs"; type = "github"; }; };
    dwarffs = { from = { id = "dwarffs"; type = "indirect"; }; to = { owner = "edolstra"; repo = "dwarffs"; type = "github"; }; };
    emacs-overlay = { from = { id = "emacs-overlay"; type = "indirect"; }; to = { owner = "nix-community"; repo = "emacs-overlay"; type = "github"; }; };
    fenix = { from = { id = "fenix"; type = "indirect"; }; to = { owner = "nix-community"; repo = "fenix"; type = "github"; }; };
    flake-parts = { from = { id = "flake-parts"; type = "indirect"; }; to = { owner = "hercules-ci"; repo = "flake-parts"; type = "github"; }; };
    flake-utils = { from = { id = "flake-utils"; type = "indirect"; }; to = { owner = "numtide"; repo = "flake-utils"; type = "github"; }; };
    gemini = { from = { id = "gemini"; type = "indirect"; }; to = { owner = "nix-community"; repo = "flake-gemini"; type = "github"; }; };
    hercules-ci-effects = { from = { id = "hercules-ci-effects"; type = "indirect"; }; to = { owner = "hercules-ci"; repo = "hercules-ci-effects"; type = "github"; }; };
    hercules-ci-agent = { from = { id = "hercules-ci-agent"; type = "indirect"; }; to = { owner = "hercules-ci"; repo = "hercules-ci-agent"; type = "github"; }; };
    home-manager = { from = { id = "home-manager"; type = "indirect"; }; to = { owner = "nix-community"; repo = "home-manager"; type = "github"; }; };
    hydra = { from = { id = "hydra"; type = "indirect"; }; to = { owner = "NixOS"; repo = "hydra"; type = "github"; }; };
    mach-nix = { from = { id = "mach-nix"; type = "indirect"; }; to = { owner = "DavHau"; repo = "mach-nix"; type = "github"; }; };
    nimble = { from = { id = "nimble"; type = "indirect"; }; to = { owner = "nix-community"; repo = "flake-nimble"; type = "github"; }; };
    nix = { from = { id = "nix"; type = "indirect"; }; to = { owner = "NixOS"; repo = "nix"; type = "github"; }; };
    nix-darwin = { from = { id = "nix-darwin"; type = "indirect"; }; to = { owner = "LnL7"; repo = "nix-darwin"; type = "github"; }; };
    nixops = { from = { id = "nixops"; type = "indirect"; }; to = { owner = "NixOS"; repo = "nixops"; type = "github"; }; };
    nixos-hardware = { from = { id = "nixos-hardware"; type = "indirect"; }; to = { owner = "NixOS"; repo = "nixos-hardware"; type = "github"; }; };
    nixos-homepage = { from = { id = "nixos-homepage"; type = "indirect"; }; to = { owner = "NixOS"; repo = "nixos-homepage"; type = "github"; }; };
    nixos-search = { from = { id = "nixos-search"; type = "indirect"; }; to = { owner = "NixOS"; repo = "nixos-search"; type = "github"; }; };
    nur = { from = { id = "nur"; type = "indirect"; }; to = { owner = "nix-community"; repo = "NUR"; type = "github"; }; };
    nixpkgs = { from = { id = "nixpkgs"; type = "indirect"; }; to = { owner = "NixOS"; ref = "nixpkgs-unstable"; repo = "nixpkgs"; type = "github"; }; };
    templates = { from = { id = "templates"; type = "indirect"; }; to = { owner = "NixOS"; repo = "templates"; type = "github"; }; };
    patchelf = { from = { id = "patchelf"; type = "indirect"; }; to = { owner = "NixOS"; repo = "patchelf"; type = "github"; }; };
    poetry2nix = { from = { id = "poetry2nix"; type = "indirect"; }; to = { owner = "nix-community"; repo = "poetry2nix"; type = "github"; }; };
    nix-serve = { from = { id = "nix-serve"; type = "indirect"; }; to = { owner = "edolstra"; repo = "nix-serve"; type = "github"; }; };
    nickel = { from = { id = "nickel"; type = "indirect"; }; to = { owner = "tweag"; repo = "nickel"; type = "github"; }; };
    bundlers = { from = { id = "bundlers"; type = "indirect"; }; to = { owner = "NixOS"; repo = "bundlers"; type = "github"; }; };
    pridefetch = { from = { id = "pridefetch"; type = "indirect"; }; to = { owner = "SpyHoodle"; repo = "pridefetch"; type = "github"; }; };
    helix = { from = { id = "helix"; type = "indirect"; }; to = { owner = "helix-editor"; repo = "helix"; type = "github"; }; };
    sops-nix = { from = { id = "sops-nix"; type = "indirect"; }; to = { owner = "Mic92"; repo = "sops-nix"; type = "github"; }; };
  };

  nixpkgs.config.allowUnfreePredicate = pkg: builtins.elem (lib.getName pkg) [
    "vscode"
  ];

  home.packages = with pkgs; [
    config.nix.package  # Per https://discourse.nixos.org/t/how-to-upgrade-nix-on-macos-with-home-manager/25147/4

    # Languages
    python311
    haskell.compiler.ghc96

    # Infra
    podman
    qemu

    # Shell
    bashInteractive

    # CLI Programs
    bat
    delta
    tldr
    tree
    visidata

    # Nix-specific Tools
    haskellPackages.nix-derivation
    nil # https://github.com/oxalica/nil#readme
    nix-direnv
    nix-info
    nix-tree
    nixpkgs-fmt
    sbomnix
    vulnix
  ];

  ##### Home-Manager Program Options ###############################################################
  programs.bash = {
    enable = true;
    profileExtra = builtins.readFile ./bash_profile;
    initExtra = builtins.readFile ./bashrc;

    ## Per https://github.com/nix-community/home-manager/issues/3133#issuecomment-1320315536
    # turn off the automated completion injection
    enableCompletion = false;
    # manually import completions using `-z` to check if it's been loaded instead of `-v`
    bashrcExtra = ''
      if [[ -z BASH_COMPLETION_VERSINFO ]]; then
        . "${pkgs.bash-completion}/etc/profile.d/bash_completion.sh"
      fi
    '';

    ## Per https://github.com/nix-community/home-manager/blob/bb4b25b302dbf0f527f190461b080b5262871756/modules/programs/bash.nix#L86
    # Modify default option set to remove macOS-incompatible options
    shellOptions = [

      # Append to history file rather than replacing it.
      "histappend"

      # check the window size after each command and, if
      # necessary, update the values of LINES and COLUMNS.
      "checkwinsize"

      # Extended globbing.
      "extglob"
      # "globstar"  # unavailable on macOS

      # Warn if closing shell with running jobs.
      # "checkjobs"  # unavailable on macOS
    ];
  };

  programs.direnv.enable = true;
  programs.direnv = {
    enableBashIntegration = true;
    nix-direnv.enable = true;
  };

  programs.exa = {
    enable = true;
  };

  programs.fzf = {
    enable = true;
    enableBashIntegration = true;
  };

  programs.git = {
    enable = true;
    includes = [{ path = "~/.config/nixpkgs/gitconfig"; }];
  };

  programs.jq.enable = true;

  # Settings adapted from https://github.com/the-argus/nixsys/blob/74ee1dd0ac503e241581ee8c3d7b719fa4305e1e/user/primary/lf.nix#L46
  programs.lf = {
    enable = true;
    settings = {
      drawbox = true;
      dirfirst = true;
      icons = true;
      ignorecase = true;
      preview = true;
      # shell = "${pkgs.dash}/bin/dash";
      # shellopts = "-eu";
      # tabstop = 2;
      # info = "size";
    };
    # previewer = {
    #   source = sandbox;
    #   keybinding = "i";
    # };
  };

  programs.nix-index.enable = true;
  programs.nix-index = {
    enableBashIntegration = true;
  };

  programs.pylint.enable = true;
  programs.pylint = {
    settings = { };
  };

  programs.vscode = {
    enable = true;
    enableUpdateCheck = false;

    userSettings = {
      "editor" = {
        "fontSize" = 18;
        "formatOnPaste" = true;
        "tabSize" = 2;
        "rulers" = [ 100 ];
      };
      "files.trimTrailingWhitespace" = true;
      "markdown.preview.doubleClickToSwitchToEditor" = false;
      "markdown.preview.openMarkdownLinks" = "inEditor";
      "[markdown]" = {
        "editor.unicodeHighlight.allowedCharacters" = {
          "’" = true;
        };
        "editor.wordWrap" = "on";
      };
      "[nix]" = {
        "editor.defaultFormatter" = "jnoortheen.nix-ide";
      };
      "nix.enableLanguageServer" = true; # Enable LSP.
      "nix.serverPath" = "nil";
      "nix.serverSettings" = {
        "nil" = {
          # "diagnostics" = {
          #   "ignored" = [ "unused_binding" "unused_with" ];
          # };
          "formatting" = {
            "command" = [ "nixpkgs-fmt" ];
          };
        };
      };
      "window.titleBarStyle" = "native";
    };

    extensions = with pkgs.vscode-extensions; [
      # Nix
      bbenoist.nix
      jnoortheen.nix-ide
      arrterian.nix-env-selector
      # Haskell
      haskell.haskell
      # Python
      ms-python.python
      # ms-python.vscode-pylance # FIXME - allowUnfree
      # Documentation
      yzhang.markdown-all-in-one
      # Configuration
      tamasfe.even-better-toml
      # Theme
      # Tooling
      eamodio.gitlens
      # General
    ]

    ++ pkgs.vscode-utils.extensionsFromVscodeMarketplace [
      {
        # MDX Preview
        name = "vscode-mdx-preview";
        publisher = "xyc";
        version = "0.2.2";
        sha256 = "sha256-76WLElIBxh7bS9H43HegZVOHNOLsPnaOv018X41JvCc=";
      }
      {
        # Mypy
        name = "mypy";
        publisher = "matangover";
        version = "0.2.2";
        sha256 = "sha256-eaiR30HjPCpOLUKQqiQ2Oqj+XY+JNnV47bM5KD2Mouk=";
      }
      {
        # Prettier JS formatter
        name = "prettier-vscode";
        publisher = "esbenp";
        version = "9.10.4";
        sha256 = "sha256-khtyB0Qbm+iuM1GsAaF32YRv1VBTIy7daeCKdgwCIC8=";
      }
      {
        # Pretty Typescript Errors
        name = "pretty-ts-errors";
        publisher = "yoavbls";
        version = "0.4.1";
        sha256 = "sha256-vY/dVO9k3LcXLYH9eX9blKMB+mDGCWkmU9ZU62YvAcM=";
      }
      {
        # Run python doctests inline like HLS
        name = "python-inline-repl";
        publisher = "zijie";
        version = "0.0.1";
        sha256 = "sha256-rn/ZR5OgDaxAGB+Q0FJ3Vx1VIAVosoZq1A5z+hptiI0=";
      }
      {
        # Language support for MDX
        name = "vscode-mdx";
        publisher = "unifiedjs";
        version = "1.3.0";
        sha256 = "sha256-TfqSU9V5vG7GwxEihUdEGC19VFHEUjlrTg+XXHdOYn4=";
      }
      {
        # Documentation with Zeal (linux kapeli/Dash.app alternetive)
        name = "vscode-dash"; # configure in vscode's settings.json through nix
        publisher = "deerawan";
        version = "2.4.0";
        sha256 = "sha256-Yqn59ppNWQRMWGYVLLWofogds+4t/WRRtSSfomPWQy4=";
      }
    ];
  };

  programs.zoxide = {
    enable = true;
    enableBashIntegration = true;
  };
}
